version: "4"

services:
  # Watchtower service to automatically update container images
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug
    networks:
      - default

  # Frontend service
  frontend:
    image: matiasfontecillaucn/frontend_proyecto_is:latest
    container_name: frontend_proyecto_is_container
    ports:
      - 80:80
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - default

  # Backend service
  backend:
    image: matiasfontecillaucn/backend_proyecto_is:latest
    container_name: backend_proyecto_is_container
    ports:
      - 5000:5000
    environment:
      db_username: ${db_username}
      db_password: ${db_password}
      db_host: mysql  # use the service name as the hostname
      db_port: ${db_port}
      db_name: ${db_name}
    depends_on:
      - mysql
    networks:
      - default

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: ${db_name}
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_PASSWORD: ${db_password}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - default

networks:
  default:

volumes:
  mysql_data:

